number = 36
slug = "036-multiline-programs"
status = "pending"
description = "Implement multi-line program storage. Line array in heap. [N] expr syntax to ..."
role = "production"
context_files = []
created_at = "2026-03-30T11:05:15"
